### ISSUE TITLE
Correct name for NERACOOS 

### ISSUE THREAD

**Issue by jakeofish** [RWSCollab/science-plan#1]
### Contact Details

jake@neracoos.org

### In what section did you find the typo?

Oceanography, and perhaps elsewhere

### Provide us with the correction for the typo.

Correct name is Northeastern Regional Association of Coastal Ocean Observing Systems (not "North East")

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eshumchenia** [comment]
Sorry about that, @jakeofish ! This was fixed in the following places:

- [3 - Marine Mammals](https://rwscollab.github.io/science-plan/marine-mammals.html)
- [8 - Habitat & Ecosystem - Oceanography](https://rwscollab.github.io/science-plan/oceanography.html)
- [Appendix A Acronyms](https://rwscollab.github.io/science-plan/append-acronyms.html)
- [Appendix J Habitat & Ecosystem - Oceanography](https://rwscollab.github.io/science-plan/append-heo.html)

see commit [d604814](https://github.com/RWSCollab/science-plan/commit/d60481422828e4c317d7c48414a424cfc56ff806)
